on: 
  push:

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.1.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
    - name: Get tag name
      id: tag-name
      run: |
        echo "tagname=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ steps.tag-name.outputs.tagname }} -t "Game" -n "Game executables ${{ steps.tag-name.outputs.tagname }}"
        gh release upload ${{ steps.tag-name.outputs.tagname }} build/**/*
